language: perl
#notifications:
#  on_success: change
#  on_failure: always
#  irc: "irc.perl.org#perlfr"
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
script:
  - perl Build.PL && ./Build test && ./Build disttest
  - perl Makefile.PL && make test
